spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres 
    password: alienxtrix
    driver-class-name: org.postgresql.Driver 
  jpa: 
    hibernate:
      ddl-auto: create
      generate-ddl: true
  show-sql: true
    
     
    
    